# Generated by Django 4.0.5 on 2022-07-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220629_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Song',
        ),
    ]
